name: lint-playbook-ci

on: [push]
jobs:
  lint-playbook-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Install Ansible'
        shell: bash
        run: |
          pip install ansible

      - name: 'Check Ansible Version'
        shell: bash
        run: |
          ansible --version
      
      - name: 'Install Ansible Lint'
        shell: bash
        run: |
          python3 -m pip install --user ansible-lint

      - name: 'Check Ansible Lint'
        shell: bash
        run: |
          ansible-lint --version

      - name: 'Run Ansible Lint'
        shell: bash
        run: |
          ansible-lint . examples/*.yml